config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    resources :microposts, :only => [:index]
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :microposts_ajax, :only => [:ajax]

  match '/users/:id/microposts' => 'microposts#index', :as => :microposts_by_user

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'
  root              :to => 'pages#home'

  get "pages/home"

  get "pages/contact"

  get "pages/about"

  get "pages/help"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user

  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true

  default_scope :order => 'microposts.created_at DESC'
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :nom, :email, :password, :password_confirmation

  has_many :microposts, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  validates :nom, :presence => true,
                  :length   => { :maximum => 50 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  # Crée automatique l'attribut virtuel 'password_confirmation'.
  validates :password, :presence => true,
            :confirmation => true,
            :length       => { :within => 6..40 }

  before_save :encrypt_password

  # Retour true (vrai) si le mot de passe correspond.
  def has_password?(password_soumis)
    encrypted_password == encrypt(password_soumis)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def feed
    # C'est un préliminaire. Cf. chapitre 12 pour l'implémentation complète.
    Micropost.where("user_id = ?", id)
  end

  private
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy


  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost ajoute"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end


  def index

    user = User.find(params[:user_id]) rescue user
    if !user.nil?
      @microposts = user.microposts.paginate(:page => params[:page])
      @titre = "Microposts de #{user.nom}"
    else
      redirect_to root_path
    end
  end

  private

  def authorized_user
    @micropost = Micropost.find(params[:id])
    redirect_to root_path unless current_user?(@micropost.user)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @titre = "Accueil"
    if signed_in?
      @micropost = Micropost.new
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
    @users = User.find(:all)

    if !params[:sel_user_id].nil?
      user = User.find(params[:sel_user_id]) rescue user

      @microposts = user.microposts unless user.nil?

      if request.xml_http_request?
        render "pages/_microposts_list"
      end


      #respond_to do |format|

      #  format.js

      #end

    end
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre = "a Propos"
  end

  def help
    @titre = 'Aide'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @titre = "S'identifier"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Combinaison mail/mot de passe invalide."
      @titre = "S'identifier"
      render 'new'
    else
      sign_in user
      redirect_back_or user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @titre = @user.nom
  end

  def new
    @user = User.new
    @titre = "Inscription"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Bienvenue dans l'Application Exemple !"
      redirect_to @user
    else
      @titre = "Inscription"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @titre = "Edition profil"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profil actualise."
      redirect_to @user
    else
      @titre = "Edition profil"
      render 'edit'
    end
  end

  def index
    @titre = "Liste des utilisateurs"
    @users = User.paginate(:page => params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Utilisateur supprime."
    redirect_to users_path
  end

  private

  def authenticate
    deny_access unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Retourner un titre basé sur la page.
  def titre
    base_titre = "Simple App du Tutoriel Ruby on Rails"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

  def logo
    image_tag("/images/logo.png", :alt => "Application exemple", :class => "round")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end


  def current_user?(user)
    user == current_user
  end


  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Merci de vous identifier pour rejoindre cette page."
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end


  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def clear_return_to
    session[:return_to] = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.nom,
                       :class => 'gravatar',
                       :gravatar => options)
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="btn btn-info"><%= link_to "À Propos", about_path %></div>
      <div class="btn btn-danger"><%= link_to "Contact", contact_path %></div>
      <div class="btn btn-success"><a href="http://news.railstutorial.org/">News</a></div>
      <div class="btn btn-warning"><a href="http://www.railstutorial.org/">Tutoriel Rails</a></div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Sample App</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Accueil", root_path %></li>
            <% if signed_in? %>
                <li><%= link_to "Utilisateurs", users_path %></li>
                <li><%= link_to "Profil", current_user %></li>
                <li><%= link_to "Réglages", edit_user_path(current_user) %></li>
            <% end %>
            <li><%= link_to "Aide", help_path %></li>
            <% if signed_in? %>
                <li><%= link_to "Déconnexion", signout_path, :method => :delete %></li>
            <% else %>
                <li><%= link_to "S'identifier", signin_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <br>


  <script src="../jquery/jquery.js"></script>
  <script src="../bootstrap/js/bootstrap.js"></script>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag '/bootstrap/css/bootstrap', :media => 'screen' %>
<%= stylesheet_link_tag '/stylesheets/nabil', :media => 'screen' %>
<%= stylesheet_link_tag '/stylesheets/screen', :media => 'screen' %>
<%= stylesheet_link_tag '/stylesheets/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag '/stylesheets/custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= titre %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application","jquery" %>

</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>
  <section class="round">
    <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posté il y a <%= time_ago_in_words(micropost.created_at) %>.
    </span>
  </td>
  <% user = micropost.user rescue User.find(micropost.user_id) %>
  <% if current_user?(user) %>
      <td>
        <%= link_to "supprimer", micropost, :method => :delete,
                    :confirm => "Etes-vous certain ?",
                    :title => micropost.content %>
      </td>
  <% end %>
</tr>

app/views/microposts/index.html.erb
<table class="microposts" summary="Microposts de l'utilisateur">
  <%= render @microposts %>
</table>
<%= will_paginate @microposts %>

app/views/pages/_microposts_list.html.erb
<table>
  <thead>
  <tr>
    <th>Microposts</th>
  </tr>
  </thead>
  <tbody>
  <% if !@microposts.nil? %>
      <% @microposts.each do |m| %>
          <tr><td><%= m.content %></td></tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/pages/about.html.erb
<h1>A propos</h1>
<p>Nabil Choual</p>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  est un projet de livre et de screencasts pour apprendre le développement web
  avec <a href="http://rubyonrails.org/">Ruby on Rails</a>. C'est l'Application Exemple de ce tutoriel.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact du Tutoriel Ruby on Rails à propos de l'Application Exemple à la
  <a href="http://railstutorial.org/feedback">page de feedback</a>.
</p>

app/views/pages/help.html.erb
<h1>Aide</h1>
<p>
  Obtenez de l'aide sur le Tutoriel Ruby on Rails sur la
  <a href="http://railstutorial.org/help">page d'aide du Tutoriel Rails</a>.
  Pour obtenir de l'aide sur cette Application Exemple, voyez le
  <a href="http://railstutorial.org/book">livre du Tutoriel Rails</a>.
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
    <table class="front" summary="Pour visiteur identifié">
      <tr>
        <td class="main">
          <h1 class="micropost">Quoi de neuf ?</h1>
          <%= render 'shared/micropost_form' %>
          <%= render 'shared/feed' %>
        </td>
        <td class="sidebar round">
          <%= render 'shared/user_info' %>
        </td>
      </tr>
    </table>
<% else %>
    <h1>Sample App</h1>

    <p>
      C'est la page d'accueil de l'application exemple du
      <a href="http://railstutorial.org/">Tutoriel Ruby on Rails</a>
      <style>
        span {
            font-weight: bold;
            color: blue;
            font-style: oblique;
            font-size: 20px;

        }
      </style>
      <script type="text/javascript">
          $(function (){
              $('span:first-child').tooltip({placement:'left'});
              $('span:last-child').tooltip();
              alert('Bienvenue à l\'application Sample App relookée avec bootstrap ' + $('#utilisateurs').val());
          });
      </script>
      <span rel="tooltip" data-original-title="relookée par Nabil le 1er Mars 2013" >relookée avec Bootstrap !</span>


    <div class="row-fluid">
      <div class="span_btn_inscription"><%= link_to "S'inscrire !", signup_path, :class => "btn btn-success btn-large" %></div>
    </div>

    <!--  Liste des utilisateurs -->

    <select id="utilisateurs" class="input-maxi">
      <%@users.each do |u| %>
          <option value= <%= u.id %>><%= u.nom %></option>
      <% end %>
    </select>

    <%= link_to "Récupérer les microposts de cet utilisateur",
        :remote => true,
        :url => "/pages/home",
        :update => "tab_microposts",
        :sel_user_id => '1'
    %>


    <!-- Tableaux des microposts de l'utilisateur selectionné -->
    <div id="tab_microposts" >
      <%= render "pages/microposts_list" %>
    </div>

<% end %>

app/views/pages/home.js.erb
$('#tab_microposts').html(<%= render :partial => "pages/microposts_list" %>);

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
      <p>There were problems with the following fields:</p>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
    <table class="microposts" summary="User microposts">
      <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
    </table>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.nom, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posté il y a <%= time_ago_in_words(feed_item.created_at) %>.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
      <td>
        <%= link_to "supprimer", feed_item, :method => :delete,
                    :confirm => "Etes-vous certain ?",
                    :title => feed_item.content %>
      </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
      <%= f.text_area :content %>
    </div>

    <button class="btn btn-info" type="submit">Soumettre</button>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.nom %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.nom, user %>
  <% if !current_user.nil? && current_user.admin? %>
      | <%= link_to "supprimer", user, :method => :delete, :confirm => "Etes-vous certain&nbsp;?",
                    :title => "Supprimer #{user.nom}" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Edition du profil</h1>

<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
      <%= f.label :nom, "Nom" %><br />
      <%= f.text_field :nom %>
    </div>
    <div class="field">
      <%= f.label :email, "eMail" %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password, "Mot de passe" %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>
<!--    <div class="actions">
      <%= f.submit "Update" %>
    </div>-->

    <button class="btn btn-info" type="submit">Mise à jour</button>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">changer</a>
</div>

app/views/users/index.html.erb
<h1>Liste des utilisateurs</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages', :object => f.object %>

    <div class="field">
      <%= f.label :nom %><br />
      <%= f.text_field :nom %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>
<!--    <div class="btn btn-info">
      <%= f.submit "Inscription" %>
    </div>-->
    <button class="btn btn-info" type="submit">Inscription</button>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nom %>
      </h1>
      <% unless @user.microposts.empty? %>
          <table class="microposts" summary="Micro-messages de l'utilisateur">
            <%= render @microposts %>
          </table>
          <%= will_paginate @microposts %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Nom</strong> <%= @user.nom %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Messages</strong>
    </td>
  </tr>
</table>